<?php

$nome_primario1 = [
'Esfera','relâmpago','chuva','orbe','elemental','raio','labareda','sangue','brilho','lança','explosão','espectro','disparo',
'revolução','parede','muralha','cristal','implosão','pirâmide','reflexo','refúgio'];

$nome_primario2 = [
'animar','controlar','destruir','despedaçar','arruinar','acalmar','distorcer','enganar','mutilar','manipular','extirpar',
'paralizar','desencantar'];

$nome_secundario1 = [
'de fogo','de gelo','da aniquilação','da discórdia','da lua','do sol','solar','estrelar','mortal','hipnótica','mental','divina',
'da matriz','da podridão','da seita','de cancer','prismático','ancestral','primordial','glacial','do rompimento'];

$nome_secundario2 = [
'mortos-vivos','animais','plantas','mentes','esperanças','ilusões','a realidade','o tempo','pessoas','corações','a alma',
'pensamentos','objetos','desejos','laços','emoções'];

$sub_nome1 = ['magia','feitiço','bruxaria'];
$sub_nome2 = ['negra', 'cinza', 'vermelha', 'rora', 'azul', 'branca','druídico','elfica','arcano','divino'];

$nome_completo = [
'Abençoar Água',
'Abraço Gélido',
'Abrir/Fechar',
'Acalmar Animal',
'Acalmar Emoções',
'Adivinhação',
'Agilidade do Gato',
'Agilidade do Gato em Massa',
'Ajuda',
'Alarme',
'Alarme Maior',
'Aliado Extraplanar',
'Aliado Extraplanar Maior',
'Aliado Extraplanar Menor',
'Alterar Forma',
'Alterar-se',
'Amaldiçoar Água',
'Amolecer Terra e Pedra',
'Amor Incontestável do Mago',
'Ampliar Animal',
'Ampliar Plantas',
'Analisar Encantamento',
'Âncora Dimensional',
'Âncora Planar',
'Âncora Planar Maior',
'Âncora Planar Menor',
'Andar no Ar',
'Andar nas Sombras',
'Animação Ilusória',
'Animar Corda',
'Animar Objetos',
'Animar Objetos',
'Animar Correntes',
'Animar Plantas',
'Antipatia',
'Ao Alcance da Mão',
'Apagar',
'Apavorante Gás do Bardo',
'Aprimorar Familiar',
'Aprisionamento',
'Aprisionar a Alma',
'Arca Secreta',
'Ardil do Conjurador',
'Área Escorregadia',
'Arma Elemental',
'Arma Elemental em Massa',
'Arma Espiritual',
'Arma Mágica',
'Arma Mágica Maior',
'Arma Mágica Suprema',
'Arma do Rompimento',
'Arma Vampírica',
'Armadilha de Corda',
'Armadilha de Fogo',
'Armadilha Ilusória',
'Armadura Arcana',
'Armadura Arcana Maior',
'Armadura Arcana Suprema',
'Arrombar',
'Aspecto do Dragão',
'Aspecto das Naghas',
'Aspecto das Sombras',
'Aspecto do Vampiro',
'Assassino Fantasmagórico',
'Astúcia da Raposa',
'Astúcia da Raposa em Massa',
'Atacar a Sorte',
'Ataque Certeiro',
'Ataque Certeiro Maior',
'Ataque Visual',
'Aterrorizar',
'Augúrio',
'Aumentar Pessoa',
'Aumentar Pessoa em Massa',
'Aura de Morte',
'Aura Mágica',
'Aura Profana',
'Aura Sagrada',
'Auxílio Divino',
'Bala de Força',
'Banimento',
'Banquete de Heróis',
'Barco Voador',
'Barreira de Lâminas',
'Benção',
'Blasfêmia',
'Boca Encantada',
'Bola de Fogo',
'Bola de Fogo Controlável',
'Bom Fruto',
'Bordão da Magia',
'Brilho',
'Buraco Negro',
'Calafrio Caótico de Nimb',
'Cajado Abençoado',
'Cajado em Cobra',
'Cajado Vivo',
'Caminhar na Água',
'Caminhar em Árvores',
'Caminhar no Vento',
'Campo Antimagia',
'Campo de Força',
'Campo de Força Maior',
'Campo de Força Menor',
'Canhão de Força',
'Cão Fiel',
'Carne para Pedra',
'Carvalho Vivo',
'Cativar',
'Causar Medo',
'Cegueira/Surdez',
'Cerrar Portas',
'Chama Contínua',
'Chamas da Força',
'Chamas da Força Maior',
'Choque Estático',
'Choque Estático Maior',
'Chuva de Meteoros',
'Chuva de Sangue',
'Chuva Quente',
'Ciclone',
'Círculo Mágico Contra o Mal',
'Círculo da Morte',
'Círculo de Teletransporte',
'Clarão do Esquecimento',
'Clarividência/Clariaudiência',
'Clone',
'Cólera da Ordem',
'Coluna de Chamas',
'Comandar',
'Comandar Maior',
'Comandar Mortos-Vivos',
'Combustão',
'Combustão em Massa',
'Compor',
'Compreender Idiomas',
'Comunhão',
'Comunhão com a Natureza',
'Condição',
'Cone Glacial',
'Confundir Detecção',
'Confusão',
'Conjuração de Sombras',
'Conjuração de Sombras Maior',
'Consagrar',
'Consertar',
'Conspurcar',
'Constrição',
'Contatar Mestre',
'Contato Extraplanar',
'Contingência',
'Conto das Rochas',
'Contra-Ataque Mental',
'Controlar Água',
'Controlar o Clima',
'Controlar Mortos-Vivos',
'Controlar os Ventos',
'Convocação Instantânea',
'Convocar Relâmpagos',
'Convocar Tempestade de Relâmpagos',
'Coordernar a Batalha',
'Coordernar a Batalha em Massa',
'Coração de Galinha',
'Corpo de Ferro',
'Corrente de Relâmpagos',
'Crânio Voador do Necromante',
'Crescer Espinhos',
'Criar Água',
'Criar Alimentos',
'Criar Chama',
'Criar Esqueletos Arcanos',
'Criar Esqueletos Arcanos Maior',
'Criar Itens Efêmeros',
'Criar Itens Temporários',
'Criar Mortos-Vivos',
'Criar Mortos-Vivos Maior',
'Criar Mortos-Vivos Menor',
'Criar Passagens',
'Cura Arcana',
'Cura Arcana Maior',
'Cura Arcana Menor',
'Cubo de Energia',
'Cúpula de Proteção contra Vegetais',
'Cúpula de Proteção contra a Vida',
'Cura Completa',
'Cura Completa em Massa',
'Curar Ferimentos Críticos',
'Curar Ferimentos Críticos em Massa',
'Curar Ferimentos Graves',
'Curar Ferimentos Graves em Massa',
'Curar Ferimentos Leves',
'Curar Ferimentos Leves em Massa',
'Curar Ferimentos Moderados',
'Curar Ferimentos Moderados em Massa',
'Dança Irresistível',
'Dedo da Morte',
'Dedo Duro',
'Descanso Tranqüilo',
'Desejo',
'Desejo Restrito',
'Desespero',
'Desespero Esmagador',
'Desintegrar',
'Deslocamento',
'Despedaçar',
'Despertar',
'Despistar',
'Destruição',
'Destruição Rastejante',
'Destruição Sagrada',
'Desmetamorfosear',
'Despestar Morto-Vivo',
'Destruir Mortos-Vivos',
'Detectar Animais',
'Detectar Armadilhas',
'Detectar Magia',
'Detectar o Mal',
'Detectar Mortos-Vivos',
'Detectar Pensamentos',
'Detectar Portas Secretas',
'Detectar Venenos',
'Detectar Vidência',
'Deteminação',
'Determinação em Massa',
'Dificultar Detecção',
'Discernir Localização',
'Discernir Mentiras',
'Disco Flutuante',
'Disco Voador',
'Disfarce Ilusório',
'Disjunção',
'Dissimular Tendência',
'Dissipar Magia',
'Dissipar Magia Maior',
'Dissipar o Mal',
'Ditado',
'Dizimar Defesas',
'Doença Plena',
'Dominação Total',
'Dominar Animal',
'Dominar Monstro',
'Dominar Pessoa',
'Domínio da Água',
'Domínio do Ar',
'Domínio do Fogo',
'Domínio do Gelo',
'Domínio da Mente',
'Domínio da Morte',
'Domínio da Terra',
'Drenar Energia',
'Drenar Força Vital',
'Drenar Temporário',
'Elucubração do Mago',
'Emanações de Paz',
'Em Chamas!',
'Empurrão Arcano',
'Encantar Arma de Osso',
'Encantar Grimório',
'Encarnação Fantasmagórica',
'Encolher Item',
'Encontrar Armadilhas',
'Encontrar o Caminho',
'Enfeitiçar Animal',
'Enfeitiçar Monstro',
'Enfeitiçar Monstro em Massa',
'Enfeitiçar Pessoa',
'Enfraquecer o Intelecto',
'Enfraquecer Plantas',
'Envelhecer',
'Envenenamento',
'Enviar Mensagem',
'Erupção do Mago',
'Escrita Ilusória',
'Escudo Arcano',
'Escudo Arcano Maior',
'Escudo Arcano Supremo',
'Escudo Entrópico',
'Escudo da Fé',
'Escudo de Fogo',
'Escudo da Ordem',
'Esculpir Som',
'Escuridão',
'Escuridão Profunda',
'Esfera Flamejante',
'Esfera Flamejante Maior',
'Esfera Gélida',
'Esfera de Invisibilidade',
'Esfera Prismática',
'Esfera Resiliente',
'Esfera Telecinética',
'Esfriar Metal',
'Espada de Energia',
'Esplendor da Águia',
'Esplendor da Águia em Massa',
'Esquentar Metal',
'Estase Temporal',
'Essência Caótica de Nimb',
'Estátua',
'Estase',
'Estase Parcial',
'Estilhaçar',
'Estrepes Mágicos',
'Estrepes Mágicos Maior',
'Evaporação',
'Exímio Esportista',
'Expandir Domínio',
'Explosão Solar',
'Explosão Sonora',
'Expulsão',
'Extinguir Fogo',
'Faísca Caótica de Nimb',
'Falar com Animais',
'Falar com os Mortos',
'Falar com Plantas',
'Fascinação',
'Feldspato Fogoso',
'Festim dos Mortos',
'Físico do Leão',
'Físico do Leão em Massa',
'Flecha Ácida',
'Flecha Ácida Maior',
'Flecha de Chamas',
'Flor Perene',
'Fogo Amigo',
'Fogo das Fadas',
'Força dos Justos',
'Força do Touro',
'Força do Touro em Massa',
'Forma Animal',
'Forma de Árvore',
'Forma Etérea',
'Forma Gasosa',
'Fumos Negros',
'Fúria',
'Gagueira do Mago',
'Galã',
'Gato Fiel',
'Gato Negro',
'Globo de Invulnerabilidade',
'Globo de Invulnerabilidade Menor',
'Globos de Luz',
'Grito',
'Grito da Banshee',
'Grito Maior',
'Grupo de Elementais',
'Heroísmo',
'Heroísmo Maior',
'Hipnotismo',
'Homens Vegetais',
'Ideia',
'Identificação',
'Idiomas',
'Imagem Maior',
'Imagem Menor',
'Imagem Permanente',
'Imagem Persistente',
'Imagem Programada',
'Imagem Silenciosa',
'Imobilizar Animal',
'Imobilizar Monstro',
'Imobilizar Monstro em Massa',
'Imobilizar Mortos-Vivos',
'Imobilizar Pessoa',
'Imobilizar Pessoa em Massa',
'Implosão',
'Imunidade a Magia',
'Imunidade a Magia Maior',
'Infligir Ferimentos Críticos',
'Infligir Ferimentos Críticos em Massa',
'Infligir Ferimentos Graves',
'Infligir Ferimentos Graves em Massa',
'Infligir Ferimentos Leves',
'Infligir Ferimentos Leves em Massa',
'Infligir Ferimentos Moderados',
'Infligir Ferimentos Moderados em Massa',
'Insanidade',
'Inseto Gigante',
'Instante de Presciência',
'Intuir Direção',
'Inverter a Gravidade',
'Invisibilidade',
'Invisibilidade Contra Animais',
'Invisibilidade Contra Mortos-Vivos',
'Invisibilidade em Massa',
'Invisibilidade Maior',
'Invisibilidade Suprema',
'Invocação Arriscada',
'Invocar Enxames',
'Invocar Monstro I',
'Invocar Monstro II',
'Invocar Monstro III',
'Invocar Monstro IV',
'Invocar Monstro V',
'Invocar Monstro VI',
'Invocar Monstro VII',
'Invocar Monstro VIII',
'Invocar Monstro IX',
'Jogo Justo',
'Labirinto',
'Lacaio-Armadilha',
'Lágrimas do Trapaceiro',
'Lágrimas da Deusa da Magia',
'Lama em Pedra',
'Lâmina Afiada',
'Lâmina Afiada em Massa',
'Lâmina Afiada Suprema',
'Lâmina Flamejante',
'Lâmina Invisível',
'Lâmina Invisível Maior',
'Lâmina Invisível Suprema',
'Lendas e Histórias',
'Lentidão',
'Leque Cromático',
'Ler Magias',
'Levitação',
'Levitação em Massa',
'Libertação',
'Ligação Telepática',
'Língua Louca',
'Limpar a Mente',
'Localizar Criatura',
'Localizar Objeto',
'Loquacidade',
'Lufada de Vento',
'Luz',
'Luz Cegante',
'Luz do Dia',
'Madeira-Ferro',
'Magia Perdida',
'Malogro',
'Manoplas De Trevas',
'Mansão Magnífica do Mago',
'Manto do Caos',
'Mão Esmagadora do Mago',
'Mão Espectral',
'Mão Interposta do Mago',
'Mão Opífera',
'Mão Poderosa do Mago',
'Mão Vigorosa do Mago',
'Mãos Flamejantes',
'Mãos Mágicas',
'Mapear',
'Marca Arcana',
'Marca da Justiça',
'Marionete',
'Martelo do Caos',
'Mata-Dragão',
'Matar',
'Medo',
'Medo do Escuro',
'Melhoria Mnemônica',
'Mensageiro Animal',
'Mensagem',
'Mente de Golfinho',
'Mente de Golfinho em Massa',
'Mesclar-se às Rochas',
'Metal em Madeira',
'Metamorfose',
'Metamorfose do Mago',
'Metamorfose',
'Metamorfose Tórrida',
'Metamorfosear Objetos',
'Meteorito de Vectorius',
'Milagre',
'Miragem Arcana',
'Missão',
'Missão Menor',
'Mísseis Mágicos',
'Mísseis Mágicos Maior',
'Mísseis Mágicos Supremo',
'Modificar Memória',
'Moldar Madeira',
'Moldar Rocha',
'Montaria Arcana',
'Montaria Fantasmagórica',
'Montaria Fantasmagórica Maior',
'Mover Terra',
'Movimentação Livre',
'Mundo dos Sonhos',
'Muralha de Energia',
'Muralha de Espinhos',
'Muralha de Ferro',
'Muralha de Fogo',
'Muralha de Gelo',
'Muralha de Pedra',
'Muralha Prismática',
'Muralha de Relâmpagos',
'Muralha de Trevas',
'Muralha de Vento',
'Muralha Sônica',
'Momento Aberrante',
'Nevasca',
'Névoa',
'Névoa Ácida',
'Névoa Fétida',
'Névoa Mental',
'Névoa Mortal',
'Névoa Obscurecente',
'Névoa Sólida',
'Nublar',
'Nuvem Incendiária',
'Nuvem Profana',
'Obscurecer Objeto',
'Olho Arcano',
'Olhos Observadores',
'Olhos Observadores Maior',
'Onda da Exaustão',
'Onda de Fadiga',
'Oração',
'Ordem',
'Orientação',
'Padrão Cintilante',
'Padrão Hipnótico',
'Padrão Prismático',
'Página Secreta',
'Palavra do Caos',
'Palavra de Poder: Atordoar',
'Palavra de Poder: Cegar',
'Palavra de Poder: Matar',
'Palavra de Recordação',
'Palavra Sagrada',
'Paradoxo dos Gêmeos',
'Parar o Tempo',
'Parede Ilusória',
'Pasmar',
'Pasmar Monstro',
'Passagem Invisível',
'Passeio Etéreo',
'Passos Longos',
'Passos sem Pegadas',
'Patas de Aranha',
'Peçonha Caótica de Nimb',
'Perecer/Prevesser',
'Perfeição dos Animais',
'Pedra em Carne',
'Pedra Encantada',
'Pedra em Lama',
'Pedras Afiadas',
'Pele de Árvore',
'Pele Rochosa',
'Penitência',
'Pequeno Refúgio',
'Perdição',
'Permanência',
'Pesadelo',
'Pirotecnia',
'Piscar',
'Poder Divino',
'Poeira Ofuscante',
'Polvo Humanoide',
'Porta Dimensional',
'Porta Dimensional Menor',
'Portal',
'Portal para o Saber',
'Praga',
'Praga de Insetos',
'Prender a Alma',
'Presa Mágica',
'Presa Mágica Maior',
'Prestidigitação',
'Prisão',
'Procastinar Ferimentos',
'Profanar',
'Proibição',
'Projeção Astral',
'Projetar Imagem',
'Proteção contra a Morte',
'Proteção contra Energia',
'Proteção contra Flechas',
'Proteção contra Flechas Maior',
'Proteção contra o Mal',
'Proteção contra Raios',
'Proteger Fortalezas',
'Proteger Outro',
'Punho Cerrado do Mago',
'Purgar Invisibilidade',
'Purificar Alimentos',
'Queda Suave',
'Raio Ardente',
'Raio de Ácido',
'Raio de Ácido Maior',
'Raio de Ácido Supremo',
'Raio do Enfraquecimento',
'Raio da Exaustão',
'Raio de Fogo',
'Raio de Frio',
'Raio de Sol',
'Raio-Fardo',
'Raio Gosmetno',
'Raio Gravitacional',
'Raio Polar',
'Raio Sônico',
'Rajada Prismática',
'Recipiente Arcano',
'Recuo Acelerado',
'Reduzir Animal',
'Reduzir Defesas',
'Reduzir Pessoa',
'Reduzir Pessoa em Massa',
'Reencarnação',
'Reflexos',
'Refugiar Itens',
'Refúgio',
'Refúgio Seguro',
'Regeneração',
'Relâmpago',
'Relâmpago Flamejante de Reynard',
'Remover Cegueira/Surdez',
'Remover da Realidade',
'Remover Doenças',
'Remover Encantamento',
'Remover Maldição',
'Remover Medo',
'Reparar Objetos',
'Reparar Objetos Maior',
'Remover Paralisia',
'Remover Veneno',
'Repelir Insetos',
'Repelir Madeira',
'Repelir Metal ou Pedra',
'Repulsão',
'Resistência',
'Resistência a Energia',
'Resistência a Magia',
'Resistência a Magia Maior',
'Respirar na Água',
'Ressurreição',
'Ressurreição Verdadeira',
'Restauração',
'Restauração Maior',
'Restauração Menor',
'Retardar Envenenamento',
'Retirada Estratégica',
'Reverter Magia',
'Reverter Magia Menor',
'Reviver os Mortos',
'Riso Histérico',
'Rocha Cadente do Mago',
'Rogar Maldição',
'Romper Morto-Vivo',
'Roupa Encantada',
'Runas Explosivas',
'Sabedoria de Coruja',
'Sabedoria de Coruja em Massa',
'Salto',
'Santificar',
'Santuário',
'Santuário Particular',
'Selo da Serpente Sépia',
'Sementes de Fogo',
'Servo Invisível',
'Servo Invisível Maior',
'Sementes Rubras',
'Servos das Trevas',
'Sexto Sentido',
'Silêncio',
'Símbolo do Atordoamento',
'Símbolo da Dor',
'Símbolo da Fraqueza',
'Símbolo da Insanidade',
'Símbolo da Morte',
'Símbolo do Medo',
'Símbolo da Persuasão',
'Símbolo de Proteção',
'Símbolo de Proteção Maior',
'Símbolo de Sangue',
'Símbolo do Sono',
'Similaridade',
'Simpatia',
'Simulacro',
'Soco Poderoso',
'Som Fantasma',
'Sombras',
'Sonho',
'Sonho de Dor',
'Sono',
'Sono Profundo',
'Sugestão',
'Sugestão em Massa',
'Super-Arcano',
'Suportar Elementos',
'Teia',
'Telecinesia',
'Teletransportar Objeto',
'Teletransporte',
'Teletransporte Ilusório',
'Teletransporte por Árvores',
'Teletransporte Maior',
'Tempestade de Fogo',
'Tempestade Glacial',
'Tempestade da Vingança',
'Tendência em Arma',
'Tentáculos Negros',
'Terremoto',
'Terreno Ilusório',
'Toque do Carniçal',
'Toque Chocante',
'Toque Chocante Maior',
'Toque da Entropia',
'Toque da Fadiga',
'Toque da Idiotice',
'Toque da Loucura',
'Toque da Múmia',
'Toque do Inumano',
'Toque do Nada',
'Toque Enferrujante',
'Toque Macabro',
'Toque Vampírico',
'Torcer Madeira',
'Tornar Inteiro',
'Traição Mágica',
'Tranca Arcana',
'Tranca Dimensional',
'Tranquilidade Impassível',
'Transe Animal',
'Transferência de Poder Divino',
'Transferir Culpa',
'Transformação de Guerra',
'Transmutar Metais',
'Transmutar Metais Maior',
'Truque da Corda',
'Universal Destroyer',
'Vazio',
'Velocidade',
'Velocidade do Relâmpago',
'Vento Dilacerador',
'Vento Sussurrante',
'Ventriloquismo',
'Ver o Invisível',
'Véu',
'Viagem no Tempo',
'Viagem Planar',
'Vidência',
'Vidência Maior',
'Vigor do Urso',
'Vigor do Urso em Massa',
'Vingança Final',
'Virtude',
'Visão',
'Visão Arcana',
'Visão Arcana Maior',
'Visão da Morte',
'Visão da Verdade',
'Visão do Caçador',
'Visão Falsa',
'Visão no Escuro',
'Visão no Escuro em Massa',
'Visão Suprema',
'Vitalidade Ilusória',
'Voltar no Tempo',
'Voltar no Tempo Maior',
'Vôo',
'Vôo Prolongado',
'Zona de Silêncio',
'Zona da Verdade'
];
